name: sandwich_shop
description: "A Flutter project for a sandwich shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/veggieDelight_footlong.png
    - assets/images/veggieDelight_six_inch.png
    - assets/images/chickenTeriyaki_footlong.png
    - assets/images/chickenTeriyaki_six_inch.png
    - assets/images/tunaMelt_footlong.png
    - assets/images/tunaMelt_six_inch.png
    - assets/images/meatballMarinara_footlong.png
    - assets/images/meatballMarinara_six_inch.png